[env:esp32-c3-super-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Швидкість завантаження та монітора порту
upload_speed = 921600
monitor_speed = 115200

; Налаштування USB CDC для виводу Serial у монітор порту
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

; Прапорці DTR/RTS для автоматичного скидання та стабільного відкриття порту
monitor_dtr = 1
monitor_rts = 1

; Необхідні бібліотеки для BNO055
lib_deps = 
	adafruit/Adafruit BNO055 @ ^1.6.3
	adafruit/Adafruit Unified Sensor @ ^1.1.14