[env:adafruit_qtpy_esp32c3]
platform = espressif32@^6.6.0
board = adafruit_qtpy_esp32c3
framework = arduino

upload_port = COM4
monitor_port = COM4
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1