[env:adafruit_qtpy_esp32c3]
platform = espressif32@^6.6.0
board = adafruit_qtpy_esp32c3
framework = arduino

; Фіксуємо робочий порт та швидкість
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200

; Ключові прапорці DTR/RTS для відкриття потоку USB CDC
monitor_dtr = 1
monitor_rts = 1

; Прапорці підтримки USB CDC для ESP32-C3
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Бібліотеки для роботи з BNO055
lib_deps = 
    wire
    SPI
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    adafruit/Adafruit BNO055 @ ^1.6.4